[package]
name = "parity-pingbot"
version = "0.1.0"
authors = ["Joseph Mark <sjeohp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
dotenv = "^0.15"
env_logger = "^0.7"
failure = "*"
futures = "0.1"
gm = { git = "https://github.com/paritytech/glitch-in-the-matrix", package="glitch-in-the-matrix" }
hyperx = "0.15.2"
log = "^0.4"
reqwest = "^0.9"
rocksdb = "0.13"
serde = "^1.0"
serde_json = "1.0.44"
snafu = { version = "0.6.0", features = ["backtraces"] }
tokio = { version = "0.2", features = ["full"] }
tokio-core = "0.1"
